### ISSUE TITLE
[FEATURE]: Add ability to pass buffer to constructor

### ISSUE THREAD

**Issue by SkeLLLa** [laslibs/las-js#13] opened 2020-04-13 11:41 UTC
**Is your feature request related to a problem? Please describe.**
In node.js there could be a case when you need to download file from some server or you can have it already in memory. So there's no need to save it to disk and pass saved path to Las constructor where it will read it again to memory.

**Describe the solution you'd like**
Constructor could be extended https://github.com/laslibs/las-js/blob/master/src/index.ts#L45.
For example, it could either take `Buffer` type as well in `path` parameter and later check if  `isNode` and `path` is Bugger, then just convert buffer to string instead of reading file from disk.

Or we could add additional parameter to constructor, something like options object where we can have `loadFile` boolean variable which will indicate if there's need to read file from somewhere or not. If `loadFile` is set to `false` `this.initialize()` could be skipped and it will be just `this.blobString = path`.

**Additional context**
I can submit PR if you're ok with such changes.

**Comment by iykekings** [comment] 2020-04-13 11:57
@SkeLLLa please submit a PR. I would love that

**Comment by Frost199** [comment] 2020-04-13 15:26
I have a concern about loading to buffer directly for files downloaded, how do you ascertain buffer size at runtime without using up computer resources, because I believe the problem is how do you allocate enough buffer size with overflowing or under-flowing the buffer, this feature is a nice one, as noted below

* Read 1 MB sequentially from memory     250,000   ns      250 us
* Read 1 MB sequentially from SSD*     1,000,000   ns    1,000 us    1 ms  ~1GB/sec SSD, 4X memory
* Read 1 MB sequentially from disk    20,000,000   ns   20,000 us   20 ms  80x memory, 20X SSD

As you can see, the memory is faster so the feature is good enough.

check this [stackoverflow post](https://stackoverflow.com/questions/4901570/buffer-vs-string-speed-why-is-string-faster) for Buffer vs strings. This is a  nice feature request I must say

**Comment by SkeLLLa** [comment] 2020-04-13 15:54
My point was just to avoid unnecessary i/o if you already have file loaded in memory. 

The best approach for speed and memory footprint is to create streaming parser, that will not need entire file. 
E.g. it could read headers to some buffer or string and parse them, but for data probably it could expose either async iterable or stream to produce object stream that could be processed line-by-line.

**Comment by Frost199** [comment] 2020-04-13 17:17
The async process was what I wanted you to point out, that could help, a pr for this feature won't be bad, the unnecessary i/o manip was what triggered me to see this as a nice FR. can a pull request be done for this? @iykekings @iambenkay @MartinsOnuoha

**Comment by iykekings** [comment] 2020-04-13 17:41
@Frost199 If I understand @SkeLLLa very well, he wants the constructor to also accept Buffer. If I'm right, then making the constructor to accept a string will suffice, then setting `Lasjs.blobString` to it. If a user has a Buffer, he can call `Buffer.toString()` on it and pass it to the constructor. @SkeLLLa, I hope this is what you are suggesting? Please feel free to correct me

**Comment by Frost199** [comment] 2020-04-13 17:55
It will be nice to set the limitations and unexpected time and space complexities in the readme for expensive operations, so uses can know what they are in for when using certain member functions or methods. but @SkeLLLa  made a good feature request and could reduce the space complexity by a great amount. I was only putting the unexpected things out there with buffers, memory leaks, computations (space and time) so if the feature request is going to merged, it will be on a lookout.

**Comment by iykekings** [comment] 2020-04-13 18:17
@Frost199 That is great suggestion. I wanted to do that earlier but the most expensive operation in the lib is O(n), which makes it trivial. My suggestion about the feature request by @SkeLLLa is to accept strings to be to be initialised as  blobString. So the lib wouldn't have to deal with memory management with buffers.

**Comment by SkeLLLa** [comment] 2020-04-13 18:41
I'm totally ok if las constructor will accept a string. That's basically what I've did in PR.

**Closed** 2020-04-15 18:29 UTC
Labels: enhancement
